// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irhikzuxugspogwquyjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyaGlrenV4dWdzcG9nd3F1eWpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1Mzk0OTAsImV4cCI6MjA4ODExNTQ5MH0.UaD56Lwk3c-GBo7xPhwWf7J0yZZOIFRZy3QsipofPGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});